name: Build and release pdf

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout this repository
      - name: Checkout this repo
        uses: actions/checkout@v2

      # Checkout the private fonts repository
#      - name: Checkout fonts repo
#        uses: actions/checkout@v2
#        with:
#          repository: betoma/fonts
#          token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
#          path: fonts

      # Builds pdf with TexLive and LuaLaTeX
      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            xelok.tex
            sound_changes/sound-change-cheatsheet.tex
            synsem_changes/synsem_change_cheatsheet.tex
          work_in_root_file_dir: true
          latexmk_use_lualatex: true
#          extra_fonts: |
          
      # Uploads zip file containing pdf(s) to the workflow tab
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: PDFs
          path: |
            xelok.pdf
            sound_changes/sound-change-cheatsheet.pdf
            synsem_changes/synsem_change_cheatsheet.pdf
      
      # Publishes pdf and license for tagged releases
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            xelok.pdf
            sound_changes/sound-change-cheatsheet.pdf
            synsem_changes/synsem_change_cheatsheet.pdf
            LICENSE
